### PR TITLE
added search bar

### LINKED ISSUE #2: Begin work on search feature
As a user I want to be able to easily search for a band by name and find information about them.

Acceptance Criteria:
- Search textbox is added to top nav
- A route called /search-results is created
- A view called search-results is created
- A SearchController is created
- Static placeholder data suffices for now
- For now all the textbox should do is take the user to the /search-results page:
  - e.g. POST /search-results, redirect to GET /search-results and display search-results view

### PR DESCRIPTION
**Pull request by wtjoe**
I tried for a while to get bootstrap to add some margin-right to that damn search bar but nothing worked!

### CODE REVIEW

**Review by jimmymccue — COMMENTED** [review]
Search bar looks good Joe.

**Review by jimmymccue — CHANGES_REQUESTED** [review]
Joe, we need the Route, Controller and View with placeholder created before merging.

**Comment by wtjoe** [comment]
Thanks Jimmy!  I added the MVC this morning and touched up the layout.  I'm happier with it!

**Review by jimmymccue — APPROVED** [review]
Nice job Joe.  It appears that you may have gotten that right margin issue taken care of. You'll have to point that out to me in the code.  I am pretty new to bootstrap.

**Pull request merged**
